import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import HomeProjectCard from "~/features/home/components/HomeProjectCard";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>CS Machine Learning</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col items-center  bg-slate-950">
        <h4 className="p-4 text-center text-2xl font-bold text-white">
          CS Machine Learning - Grupo ni Reginald
        </h4>
        <div className="container m-auto grid h-full grid-cols-1 place-content-center gap-4 sm:grid-cols-2 md:grid-cols-4">
          <HomeProjectCard
            className="delay-100"
            title="Medical Insurance Prediction Model"
            description="Quiz 2 - Part 1"
            link="/quiz_2/part_1"
            content={
              <p>
                This contains the application for the medical insturance
                prediction engine
              </p>
            }
          />
          <HomeProjectCard
            className="delay-300"
            title="Heart Attack Prediction Model"
            description="Quiz 2 - Part 2"
            link="/quiz_2/part_2"
            content={
              <p>
                This contains the application for the heart disease prediction
                engine
              </p>
            }
          />
        </div>
      </main>
    </>
  );
};

export default Home;
